RUN apt-get update && apt-get install --fix-missing -y \
    aptitude \
    build-essential \
    curl \
    dpkg-dev \
    gfortran \
    gcc \
    git \
    libjpeg-dev \
    libpng-dev \
    libtirpc-dev \
    libtk-img \
    libx11-dev \
    libxext-dev \
    libxft-dev \
    libxt-dev \
    libxpm-dev \
    libgl1-mesa-dev \
    libxtst-dev \
    libxrender-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxcomposite-dev \
    libxdamage-dev \
    libxi-dev \
    libexpat1-dev \
    libmotif-dev \
    libgd-perl \
    libnetpbm10-dev \
    lsb-release \
    make \
    ncftp \
    perl \
    perl-tk \
    software-properties-common \
    sudo \
    tk \
    vim \
    wget \
    xorg \
    imagemagick \
    expect \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*
